### ISSUE TITLE
Todo List 2

### ISSUE THREAD

**Issue by inclinedadarsh** [inclinedadarsh/portfolio#11]
- [x] Add Favicon
- [x] Add OG Tags and Image
- [x] Add "Currently in development" page
- [x] Fix the button size - preferably make a button component
- [x] Fix the navigation bar colors
