### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by inclinedadarsh** [inclinedadarsh/portfolio#3]
# Todo List

Todo list of all the work that's left to do

- [x] Add Font General Sans font
- [x] Create **Projects** section
- [x] Create **Blogs** section
- [x] Create **Contact** section
- [x] Create **Footer**
